// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SnapShooter;

{ITE} {DFMFileType} {UMain.dfm}
{ITE} {RCFileType} {SnapShooter_DRC.rc}

{$R 'UMain.dfm' 'FrmMain:TForm'}
{$R 'SnapShooter_DRC.res' 'SnapShooter_DRC.rc'}

{$E ENU}

begin
end.
